name: EPG Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1,7,13,19 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史
    
    - name: Update EPG Files
      id: update
      run: |
        # 使用临时文件避免部分下载
        temp_file=$(mktemp)
        wget -nv -O "$temp_file" https://raw.githubusercontent.com/kuke31/xmlgz/main/e.xml
        
        # 检查文件是否有效（非空且包含XML声明）
        if [ -s "$temp_file" ] && grep -q '<?xml' "$temp_file"; then
          # 只在内容变更时更新
          if ! cmp -s "$temp_file" epg.xml; then
            mv "$temp_file" epg.xml
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "内容未变化，跳过更新"
            rm -f "$temp_file"
          fi
        else
          echo "::error::下载的文件无效或为空"
          rm -f "$temp_file"
          exit 1
        fi

    - name: Commit changes
      if: ${{ env.changed == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git commit -m "EPG更新: $(date +'%Y-%m-%d %H:%M:%S')"
        
    - name: Push changes
      if: ${{ env.changed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false
